### ISSUE TITLE
Issues with svg or canvas

### ISSUE THREAD

**Issue by maddyjolly2112** [ymkins/html2pdfmake#7]
Can you let us know how to handle canvas or svg, i tried converting the svg or canvas to base64 and pushing into the content but it didn't worked. It paste the whole base64 code into the pdf.

Any help will be highly appreciated !!

**Comment by maddyjolly2112** [comment]
I solved it by editing the library and also using it with pdfmake, it works like charm.

**Comment by maddyjolly2112** [comment]
I solved it by editing the library and also using it with pdfmake, it works like charm.

**Comment by j-funk** [comment]
@maddyjolly2112 can you share how you made SVG work?

**Comment by maddyjolly2112** [comment]
@j-funk , please find below :

```
Case 'SVG' : 
 addImage(cnt,e);

function addImage (cnt,e) {
            //Serialize the svg element and then put it in a canvas
//Then update the cnt object
var url = canvas.toDataURL('image/png');
        cnt.push({image: url,
              width: 200,
              height: 250,
              margin: [ 20, 0, 0, 0 ]
        });
}
```
